# /// script
# requires-python = ">=3.11"
# ///
"""Compile the vendored Public Suffix List into a C++ rule table.

Reads third_party/psl/public_suffix_list.dat (upstream, verbatim) and writes
third_party/psl/psl_rules.cpp next to it. The transformation is mechanical:
comments and blank lines go, every remaining line is one rule, and the rules
keep their '!' / '*.' prefixes and their Unicode spelling — the extension
classifies the prefixes and converts Unicode rules to punycode through ada's
own IDNA at load time, so no second IDNA implementation exists here.

Bytes above ASCII are emitted as octal escapes: an octal escape is exactly
three digits, so it cannot swallow the character that follows, and the source
file stays pure ASCII regardless of what a compiler assumes about its encoding.

Run after refreshing the .dat (see docs/UPDATING.md):

    uv run scripts/generate_psl.py
"""

from pathlib import Path

PSL_DIR = Path(__file__).resolve().parents[1] / "third_party" / "psl"
LIST_PATH = PSL_DIR / "public_suffix_list.dat"
SOURCE_PATH = PSL_DIR / "psl_rules.cpp"


def c_literal(rule: str) -> str:
    escaped = "".join(chr(byte) if byte < 0x80 else f"\\{byte:03o}" for byte in rule.encode())
    return f'"{escaped}"'


def main() -> None:
    rules = [
        stripped
        for stripped in (line.strip() for line in LIST_PATH.read_text(encoding="utf-8").splitlines())
        if stripped and not stripped.startswith("//")
    ]
    body = "\n".join(f"    {c_literal(rule)}," for rule in rules)
    SOURCE_PATH.write_text(
        f"""// GENERATED by scripts/generate_psl.py from public_suffix_list.dat -- do not edit.
// The list itself (Public Suffix List, MPL-2.0) is vendored next to this file; see
// docs/THIRD_PARTY_NOTICES.md for its pinned version and license, docs/UPDATING.md to refresh it.

#include "psl_rules.h"

namespace url_tools_psl {{

const char *const PUBLIC_SUFFIX_RULES[] = {{
{body}
}};

const size_t PUBLIC_SUFFIX_RULE_COUNT = {len(rules)};

}} // namespace url_tools_psl
""",
        encoding="ascii",
    )
    print(f"{SOURCE_PATH.relative_to(Path.cwd())}: {len(rules)} rules")


if __name__ == "__main__":
    main()
